export const FETCH_AUCTIONS_REQUEST = 'FETCH_AUCTIONS_REQUEST';
export const FETCH_AUCTIONS_SUCCESS = 'FETCH_AUCTIONS_SUCCESS';
export const FETCH_AUCTIONS_FAILURE = 'FETCH_AUCTIONS_FAILURE';

export const FETCH_AUCTION_REQUEST = 'FETCH_AUCTION_REQUEST';
export const FETCH_AUCTION_SUCCESS = 'FETCH_AUCTION_SUCCESS';
export const FETCH_AUCTION_FAILURE = 'FETCH_AUCTION_FAILURE';
